---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec
  inspec_tests:
    - compliance://cis/cis-ubuntu14.04lts-level1

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ufw::default]
    attributes:
